// Code generated by admin:make-resource. DO NOT EDIT.
import type { RouteRecordRaw } from 'vue-router'
import ResourceListPage from '@/core/resource/pages/ResourceListPage.vue'
import ResourceFormPage from '@/core/resource/pages/ResourceFormPage.vue'
import ResourceDetailPage from '@/core/resource/pages/ResourceDetailPage.vue'
import { resourceDefinition as announcementsResource } from '@/modules/announcements/resource'
import { resourceDefinition as departmentsResource } from '@/modules/departments/resource'

export interface GeneratedResourceDefinition {
  name: string
  label: string
  admin_route: string
  api_base: string
  permission: string
  icon: string
  pageMode: 'generic' | 'custom'
  navigation: { group: string; order: number; hidden?: boolean }
}

export const generatedResourceDefinitions = [
  announcementsResource,
  departmentsResource,
] as const

export const generatedResourceRoutes: RouteRecordRaw[] = [
  { path: announcementsResource.admin_route, name: "announcements-resource-list", props: { resource: announcementsResource.name }, meta: { permission: announcementsResource.permission }, component: ResourceListPage },
  { path: announcementsResource.admin_route + '/new', name: "announcements-resource-create", props: { resource: announcementsResource.name }, meta: { permission: announcementsResource.permission }, component: ResourceFormPage },
  { path: announcementsResource.admin_route + '/:id/edit', name: "announcements-resource-edit", props: { resource: announcementsResource.name }, meta: { permission: announcementsResource.permission }, component: ResourceFormPage },
  { path: announcementsResource.admin_route + '/:id', name: "announcements-resource-detail", props: { resource: announcementsResource.name }, meta: { permission: announcementsResource.permission }, component: ResourceDetailPage },
  { path: departmentsResource.admin_route, name: "departments-resource-list", props: { resource: departmentsResource.name }, meta: { permission: departmentsResource.permission }, component: ResourceListPage },
  { path: departmentsResource.admin_route + '/new', name: "departments-resource-create", props: { resource: departmentsResource.name }, meta: { permission: departmentsResource.permission }, component: ResourceFormPage },
  { path: departmentsResource.admin_route + '/:id/edit', name: "departments-resource-edit", props: { resource: departmentsResource.name }, meta: { permission: departmentsResource.permission }, component: ResourceFormPage },
  { path: departmentsResource.admin_route + '/:id', name: "departments-resource-detail", props: { resource: departmentsResource.name }, meta: { permission: departmentsResource.permission }, component: ResourceDetailPage },
]
