// Code generated by admin:make-resource. DO NOT EDIT.
import type { RouteRecordRaw } from 'vue-router'
import { resourceDefinition as announcementsResource } from '@/modules/announcements/resource'
import AnnouncementsListPage from '@/modules/announcements/pages/AnnouncementsListPage.vue'
import AnnouncementsFormPage from '@/modules/announcements/pages/AnnouncementsFormPage.vue'
import AnnouncementsDetailPage from '@/modules/announcements/pages/AnnouncementsDetailPage.vue'

export interface GeneratedResourceDefinition {
  name: string
  label: string
  route: string
  permission: string
  icon: string
  navigation: { group: string; order: number; hidden?: boolean }
}

export const generatedResourceDefinitions = [
  announcementsResource,
] as const

export const generatedResourceRoutes: RouteRecordRaw[] = [
  { path: announcementsResource.route, name: "announcements-resource-list", meta: { permission: announcementsResource.permission }, component: AnnouncementsListPage },
  { path: announcementsResource.route + '/new', name: "announcements-resource-create", meta: { permission: announcementsResource.permission }, component: AnnouncementsFormPage },
  { path: announcementsResource.route + '/:id/edit', name: "announcements-resource-edit", meta: { permission: announcementsResource.permission }, component: AnnouncementsFormPage },
  { path: announcementsResource.route + '/:id', name: "announcements-resource-detail", meta: { permission: announcementsResource.permission }, component: AnnouncementsDetailPage },
]
