package generator

import (
	"fmt"
	"path/filepath"
	"strings"
)

func RenderFrontend(spec Spec) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("admin", "src", "modules", spec.Name))
	pageBase := filepath.ToSlash(filepath.Join(base, "pages"))
	files := []struct {
		path string
		body string
	}{
		{filepath.Join(base, "resource.ts"), frontendResourceSource(spec)},
		{filepath.Join(base, "api.ts"), frontendAPISource(spec)},
		{filepath.Join(pageBase, spec.GoName+"ListPage.vue"), frontendListPageSource(spec)},
		{filepath.Join(pageBase, spec.GoName+"FormPage.vue"), frontendFormPageSource(spec)},
		{filepath.Join(pageBase, spec.GoName+"DetailPage.vue"), frontendDetailPageSource(spec)},
		{filepath.Join(base, spec.Name+".test.ts"), frontendTestSource(spec)},
	}
	artifacts := make([]Artifact, 0, len(files))
	for _, file := range files {
		artifacts = append(artifacts, Artifact{Path: filepath.ToSlash(file.path), Content: []byte(file.body)})
	}
	return artifacts, nil
}

func frontendResourceSource(spec Spec) string {
	scopeMetadata := ""
	if spec.DataScope == "own" {
		scopeMetadata = fmt.Sprintf("  dataScope: %q,\n  ownerField: %q,\n", spec.DataScope, spec.OwnerField)
	}
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: %q,
  label: %q,
  route: %q,
  permission: %q,
  icon: %q,
  navigation: { group: "business", order: 100 },
%s
  actions: %s,
  relations: %s,
  form_groups: %s,
  details: %s,
  fields: %s,
} as const;
`, spec.Name, spec.Label, spec.FrontendRoute, spec.Permission, spec.Icon, scopeMetadata, frontendActionList(spec), frontendRelations(spec), frontendFormGroups(spec), frontendDetails(spec), frontendFields(spec))
}

func frontendMenuSource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import { resourceDefinition } from './resource';

export const menuEntry = {
  label: resourceDefinition.label,
  route: resourceDefinition.route,
  permission: resourceDefinition.permission,
  icon: resourceDefinition.icon,
  navigation: resourceDefinition.navigation,
} as const;
`)
}

func frontendAPISource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import { generatedApi } from '@/generated/api';

export type ResourceRecord = Record<string, unknown>;
export type ResourceList<T = ResourceRecord> = { data: T[]; meta?: Record<string, unknown> };

export const resourceApi = {
  list(query: URLSearchParams, token: string) {
    return generatedApi.resourceList<ResourceRecord>(%q, query, token) as unknown as Promise<ResourceList>;
  },
  show(id: string | number, token: string) {
    return generatedApi.resourceShow<ResourceRecord>(%q, id, token);
  },
  create(payload: ResourceRecord, token: string) {
    return generatedApi.resourceCreate<ResourceRecord>(%q, payload, token);
  },
  update(id: string | number, payload: ResourceRecord, token: string) {
    return generatedApi.resourceUpdate<ResourceRecord>(%q, id, payload, token);
  },
  relationOptions(relation: string, token: string) {
    return generatedApi.resourceRelationOptions(%q, relation, token);
  },
  remove(id: string | number, token: string) {
    return generatedApi.resourceDelete(%q, id, token);
  },
};
`, spec.Name, spec.Name, spec.Name, spec.Name, spec.Name, spec.Name)
}

func frontendRoutesSource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import type { RouteRecordRaw } from 'vue-router';
import %sListPage from './pages/%sListPage.vue';
import %sFormPage from './pages/%sFormPage.vue';
import %sDetailPage from './pages/%sDetailPage.vue';

// Register resourceRoutes in the application router after review.
export const resourceRoutes: RouteRecordRaw[] = [
  { path: %q, component: %sListPage },
  { path: %q, component: %sFormPage },
  { path: %q, component: %sFormPage },
  { path: %q, component: %sDetailPage },
];
`, spec.GoName, spec.GoName, spec.GoName, spec.GoName, spec.GoName, spec.GoName,
		spec.FrontendRoute, spec.GoName, spec.FrontendRoute+"/new", spec.GoName,
		spec.FrontendRoute+"/:id/edit", spec.GoName, spec.FrontendRoute+"/:id", spec.GoName)
}

func frontendListPageSource(spec Spec) string {
	return fmt.Sprintf(`<script setup lang="ts">
import ResourceListView from '@/core/resource/pages/ResourceListPage.vue';
</script>

<!-- Generated resource page. Register its route only after reviewing the resource contract. -->
<template>
  <ResourceListView resource=%q />
</template>
`, spec.Name)
}

func frontendFormPageSource(spec Spec) string {
	return `<script setup lang="ts">
import ResourceFormView from '@/components/resource/ResourceFormView.vue';
import { resourceApi } from '../api';
import { resourceDefinition } from '../resource';
</script>

<!-- Generated resource form. Register the route and matching backend contract after review. -->
<template>
  <ResourceFormView :resource="resourceDefinition" :api="resourceApi" />
</template>
`
}

func frontendDetailPageSource(spec Spec) string {
	return fmt.Sprintf(`<script setup lang="ts">
import ResourceDetailView from '@/core/resource/pages/ResourceDetailPage.vue';
</script>

<!-- Generated resource page. Register its route only after reviewing the resource contract. -->
<template>
  <ResourceDetailView resource=%q />
</template>
`, spec.Name)
}

func frontendTestSource(spec Spec) string {
	return fmt.Sprintf(`import { resourceDefinition } from './resource';

// This contract check uses the existing Node type/runtime surface; the generator
// does not add a frontend test-runner dependency.
if (resourceDefinition.name !== %q) throw new Error('generated resource name mismatch');
if (resourceDefinition.route !== %q) throw new Error('generated resource route mismatch');
if (JSON.stringify(resourceDefinition.actions) !== JSON.stringify(%s)) throw new Error('generated resource actions mismatch');
`, spec.Name, spec.FrontendRoute, frontendActionList(spec))
}

func frontendFields(spec Spec) string {
	parts := make([]string, 0, len(spec.Fields))
	for _, field := range spec.Fields {
		options := ""
		if len(field.Options) > 0 {
			values := make([]string, 0, len(field.Options))
			for _, option := range field.Options {
				values = append(values, fmt.Sprintf("{ value: %q, label: %q }", option.Value, option.Label))
			}
			options = ", options: [" + strings.Join(values, ", ") + "]"
		}
		parts = append(parts, fmt.Sprintf("{ name: %q, label: %q, type: %q, required: %t, visible: %t, readable: %t, writable: %t, sensitive: %t%s }", field.Name, humanize(field.Name), field.Type, field.Required, fieldBool(field.Visible), fieldBool(field.Readable), fieldBool(field.Writable), field.Sensitive, options))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func quoteList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func frontendActionList(spec Spec) string {
	items := make([]string, 0, len(spec.ActionSpecs))
	for _, action := range spec.ActionSpecs {
		items = append(items, fmt.Sprintf("{ name: %q, label: %q, kind: %q, permission: %q, batch: %t, payload: %q }", action.Name, action.Label, action.Kind, action.Permission, action.Batch, action.Payload))
	}
	return "[" + strings.Join(items, ", ") + "]"
}

func frontendRelations(spec Spec) string {
	items := make([]string, 0, len(spec.Relations))
	for _, relation := range spec.Relations {
		items = append(items, fmt.Sprintf("{ name: %q, kind: %q, resource: %q, field: %q, foreign_field: %q, label_field: %q, selectable: %t, multiple: false }", relation.Name, relation.Kind, relation.Resource, relation.Field, relation.ForeignField, relation.LabelField, relation.Selectable))
	}
	return "[" + strings.Join(items, ", ") + "]"
}

func frontendFormGroups(spec Spec) string {
	items := make([]string, 0, len(spec.FormGroups))
	for _, group := range spec.FormGroups {
		items = append(items, fmt.Sprintf("{ name: %q, label: %q, columns: %d, fields: %s }", group.Name, group.Label, group.Columns, quoteList(group.Fields)))
	}
	return "[" + strings.Join(items, ", ") + "]"
}

func frontendDetails(spec Spec) string {
	items := make([]string, 0, len(spec.Details))
	for _, section := range spec.Details {
		items = append(items, fmt.Sprintf("{ name: %q, label: %q, fields: %s }", section.Name, section.Label, quoteList(section.Fields)))
	}
	return "[" + strings.Join(items, ", ") + "]"
}
