package generator

import (
	"fmt"
	"path/filepath"
	"strings"
)

func RenderFrontend(spec Spec) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("admin", "src", "modules", spec.Name))
	pageBase := filepath.ToSlash(filepath.Join(base, "pages"))
	files := []struct {
		path string
		body string
	}{
		{filepath.Join(base, "resource.ts"), frontendResourceSource(spec)},
		{filepath.Join(base, "api.ts"), frontendAPISource(spec)},
		{filepath.Join(pageBase, spec.GoName+"ListPage.vue"), frontendListPageSource(spec)},
		{filepath.Join(pageBase, spec.GoName+"FormPage.vue"), frontendFormPageSource(spec)},
		{filepath.Join(pageBase, spec.GoName+"DetailPage.vue"), frontendDetailPageSource(spec)},
		{filepath.Join(base, spec.Name+".test.ts"), frontendTestSource(spec)},
	}
	artifacts := make([]Artifact, 0, len(files))
	for _, file := range files {
		artifacts = append(artifacts, Artifact{Path: filepath.ToSlash(file.path), Content: []byte(file.body)})
	}
	return artifacts, nil
}

func frontendResourceSource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: %q,
  label: %q,
  route: %q,
  permission: %q,
  icon: %q,
  actions: %s,
  fields: %s,
} as const;
`, spec.Name, spec.Label, spec.FrontendRoute, spec.Permission, spec.Icon, quoteList(spec.Actions), frontendFields(spec))
}

func frontendMenuSource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import { resourceDefinition } from './resource';

export const menuEntry = {
  label: resourceDefinition.label,
  route: resourceDefinition.route,
  permission: resourceDefinition.permission,
  icon: resourceDefinition.icon,
} as const;
`)
}

func frontendAPISource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import { apiFetch, apiFetchEnvelope } from '@/lib/api';

export type ResourceRecord = Record<string, unknown>;
export type ResourceList<T = ResourceRecord> = { data: T[]; meta?: Record<string, unknown> };

const basePath = '/api/v1/admin/resources/%s';

export const resourceApi = {
  list(query: URLSearchParams, token: string) {
    return apiFetchEnvelope<ResourceRecord[]>(basePath + '?' + query, {}, token) as unknown as Promise<ResourceList>;
  },
  show(id: string | number, token: string) {
    return apiFetch<ResourceRecord>(basePath + '/' + id, {}, token);
  },
  create(payload: ResourceRecord, token: string) {
    return apiFetch<ResourceRecord>(basePath, { method: 'POST', body: JSON.stringify(payload) }, token);
  },
  update(id: string | number, payload: ResourceRecord, token: string) {
    return apiFetch<ResourceRecord>(basePath + '/' + id, { method: 'PUT', body: JSON.stringify(payload) }, token);
  },
  remove(id: string | number, token: string) {
    return apiFetch<void>(basePath + '/' + id, { method: 'DELETE' }, token);
  },
};
`, spec.Name)
}

func frontendRoutesSource(spec Spec) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import type { RouteRecordRaw } from 'vue-router';
import %sListPage from './pages/%sListPage.vue';
import %sFormPage from './pages/%sFormPage.vue';
import %sDetailPage from './pages/%sDetailPage.vue';

// Register resourceRoutes in the application router after review.
export const resourceRoutes: RouteRecordRaw[] = [
  { path: %q, component: %sListPage },
  { path: %q, component: %sFormPage },
  { path: %q, component: %sFormPage },
  { path: %q, component: %sDetailPage },
];
`, spec.GoName, spec.GoName, spec.GoName, spec.GoName, spec.GoName, spec.GoName,
		spec.FrontendRoute, spec.GoName, spec.FrontendRoute+"/new", spec.GoName,
		spec.FrontendRoute+"/:id/edit", spec.GoName, spec.FrontendRoute+"/:id", spec.GoName)
}

func frontendListPageSource(spec Spec) string {
	return fmt.Sprintf(`<script setup lang="ts">
import ResourceListView from '@/core/resource/pages/ResourceListPage.vue';
</script>

<!-- Generated resource page. Register its route only after reviewing the resource contract. -->
<template>
  <ResourceListView resource=%q />
</template>
`, spec.Name)
}

func frontendFormPageSource(spec Spec) string {
	return `<script setup lang="ts">
import ResourceFormView from '@/components/resource/ResourceFormView.vue';
import { resourceApi } from '../api';
import { resourceDefinition } from '../resource';
</script>

<!-- Generated resource form. Register the route and matching backend contract after review. -->
<template>
  <ResourceFormView :resource="resourceDefinition" :api="resourceApi" />
</template>
`
}

func frontendDetailPageSource(spec Spec) string {
	return fmt.Sprintf(`<script setup lang="ts">
import ResourceDetailView from '@/core/resource/pages/ResourceDetailPage.vue';
</script>

<!-- Generated resource page. Register its route only after reviewing the resource contract. -->
<template>
  <ResourceDetailView resource=%q />
</template>
`, spec.Name)
}

func frontendTestSource(spec Spec) string {
	return fmt.Sprintf(`import { describe, expect, it } from 'vitest';
import { resourceDefinition } from './resource';

describe('%s resource metadata', () => {
  it('keeps the generated identity and actions', () => {
    expect(resourceDefinition.name).toBe(%q);
    expect(resourceDefinition.route).toBe(%q);
    expect(resourceDefinition.actions).toEqual(%s);
  });
});
`, spec.Name, spec.Name, spec.FrontendRoute, quoteList(spec.Actions))
}

func frontendFields(spec Spec) string {
	parts := make([]string, 0, len(spec.Fields))
	for _, field := range spec.Fields {
		options := ""
		if len(field.Options) > 0 {
			values := make([]string, 0, len(field.Options))
			for _, option := range field.Options {
				values = append(values, fmt.Sprintf("{ value: %q, label: %q }", option.Value, option.Label))
			}
			options = ", options: [" + strings.Join(values, ", ") + "]"
		}
		parts = append(parts, fmt.Sprintf("{ name: %q, label: %q, type: %q, required: %t%s }", field.Name, humanize(field.Name), field.Type, field.Required, options))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func quoteList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
