package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
)

type MenuInput struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

type MenuSpec struct {
	Name       string
	GoName     string
	Label      string
	Route      string
	Permission string
	Icon       string
}

func NormalizeMenu(input MenuInput) (MenuSpec, error) {
	if !resourceNamePattern.MatchString(input.Name) {
		return MenuSpec{}, fmt.Errorf("invalid menu name %q", input.Name)
	}
	if strings.TrimSpace(input.Label) == "" {
		return MenuSpec{}, fmt.Errorf("menu %q requires a label", input.Name)
	}
	if input.Route == "" || !strings.HasPrefix(input.Route, "/") || strings.Contains(input.Route, "..") {
		return MenuSpec{}, fmt.Errorf("invalid menu route %q", input.Route)
	}
	if !strings.HasPrefix(input.Permission, "admin.") {
		return MenuSpec{}, fmt.Errorf("invalid menu permission %q", input.Permission)
	}
	if strings.TrimSpace(input.Icon) == "" {
		return MenuSpec{}, fmt.Errorf("menu %q requires an icon", input.Name)
	}
	return MenuSpec{Name: input.Name, GoName: pascal(input.Name), Label: input.Label, Route: input.Route, Permission: input.Permission, Icon: input.Icon}, nil
}

func RenderMenu(spec MenuSpec) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("app", "modules", spec.Name, "menu"))
	source := fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package menus

type Entry struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

var %s = Entry{Name: %q, Label: %q, Route: %q, Permission: %q, Icon: %q}
`, spec.GoName, spec.Name, spec.Label, spec.Route, spec.Permission, spec.Icon)
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format menu: %w", err)
	}
	readme := fmt.Sprintf(`# %s menu

This menu entry was generated as part of `+"`admin:make-resource`"+`.

- Label: `+"`%s`"+`
- Route: `+"`%s`"+`
- Permission: `+"`%s`"+`
- Icon: `+"`%s`"+`

Register this entry manually in the approved navigation/Sidebar configuration after reviewing the route and permission. This generator does not modify frontend routes, menus, permissions, or the database.
`, spec.Name, spec.Label, spec.Route, spec.Permission, spec.Icon)
	return []Artifact{
		{Path: filepath.ToSlash(filepath.Join(base, "menu.go")), Content: formatted},
		{Path: filepath.ToSlash(filepath.Join(base, "README.md")), Content: []byte(readme)},
	}, nil
}
