package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
)

func RenderModule(spec ModuleSpec) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("app", "modules", spec.Name))
	packageName := strings.ReplaceAll(spec.Name, "-", "_")
	files := []struct {
		path string
		body string
	}{
		{"module.go", fmt.Sprintf(`// Code generated by admin:make-module. DO NOT EDIT.
package %s

type Module struct{}

func (Module) Name() string { return %q }
`, packageName, spec.Name)},
		{"model.go", moduleBoundarySource(packageName, "Model")},
		{"request.go", moduleBoundarySource(packageName, "Request")},
		{"repository.go", moduleBoundarySource(packageName, "Repository")},
		{"service.go", moduleBoundarySource(packageName, "Service")},
		{"controller.go", moduleBoundarySource(packageName, "Controller")},
		{"routes.go", moduleBoundarySource(packageName, "Routes")},
		{"resource.go", moduleBoundarySource(packageName, "Resource")},
		{"permissions.go", moduleBoundarySource(packageName, "Permissions")},
		{"events.go", moduleBoundarySource(packageName, "Events")},
		{"tests/module_test.go", fmt.Sprintf(`// Code generated by admin:make-module. DO NOT EDIT.
package %s_test

import "testing"

func TestModuleBoundaryExists(t *testing.T) {
	t.Skip("implement module behavior after manual runtime registration")
}
`, packageName)},
		{"README.md", moduleReadmeSource(spec)},
	}

	artifacts := make([]Artifact, 0, len(files))
	for _, file := range files {
		content := []byte(file.body)
		if filepath.Ext(file.path) == ".go" {
			formatted, err := format.Source(content)
			if err != nil {
				return nil, fmt.Errorf("format %s: %w", file.path, err)
			}
			content = formatted
		}
		artifacts = append(artifacts, Artifact{Path: filepath.ToSlash(filepath.Join(base, file.path)), Content: content})
	}
	return artifacts, nil
}

func moduleReadmeSource(spec ModuleSpec) string {
	return fmt.Sprintf(`# %s module

This module was generated by `+"`admin:make-module`"+`.

## Next steps

1. Review the generated boundaries and implement the module's business behavior.
2. Register the module Provider manually when its lifecycle is ready.
3. Register routes, permissions, menus, and Resource Registry entries manually.
4. Add and review any database migration separately; this generator does not create or execute migrations.

Useful commands from `+"`backend/`"+`:

`+"```text"+`
go test ./app/modules/%s/...
go run . artisan admin:check-module %s
`+"```"+`

Generated files are intentionally inert until the runtime registration is reviewed.
`, spec.Name, spec.Name, spec.Name)
}

func moduleBoundarySource(packageName, typeName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-module. DO NOT EDIT.
package %s

type %s struct{}
`, packageName, typeName)
}
