package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
)

func RenderModule(spec ModuleSpec) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("app", "modules", spec.Name))
	packageName := strings.ReplaceAll(spec.Name, "-", "_")
	files := []struct {
		path string
		body string
	}{
		{"module.go", fmt.Sprintf(`// Code generated by admin:make-module. DO NOT EDIT.
package %s

type Module struct{}

func (Module) Name() string { return %q }
`, packageName, spec.Name)},
		{"model.go", moduleBoundarySource(packageName, "Model")},
		{"request.go", moduleBoundarySource(packageName, "Request")},
		{"repository.go", moduleBoundarySource(packageName, "Repository")},
		{"service.go", moduleBoundarySource(packageName, "Service")},
		{"controller.go", moduleBoundarySource(packageName, "Controller")},
		{"routes.go", moduleBoundarySource(packageName, "Routes")},
		{"resource.go", moduleBoundarySource(packageName, "Resource")},
		{"permissions.go", moduleBoundarySource(packageName, "Permissions")},
		{"events.go", moduleBoundarySource(packageName, "Events")},
		{"tests/module_test.go", fmt.Sprintf(`// Code generated by admin:make-module. DO NOT EDIT.
package %s_test

import "testing"

func TestModuleBoundaryExists(t *testing.T) {
	t.Skip("implement module behavior after manual runtime registration")
}
`, packageName)},
	}

	artifacts := make([]Artifact, 0, len(files))
	for _, file := range files {
		content, err := format.Source([]byte(file.body))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", file.path, err)
		}
		artifacts = append(artifacts, Artifact{Path: filepath.ToSlash(filepath.Join(base, file.path)), Content: content})
	}
	return artifacts, nil
}

func moduleBoundarySource(packageName, typeName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-module. DO NOT EDIT.
package %s

type %s struct{}
`, packageName, typeName)
}
