package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
)

var supportedPermissionActions = map[string]struct{}{
	"view": {}, "create": {}, "update": {}, "delete": {}, "manage": {},
}

type PermissionInput struct {
	Name    string
	Actions []string
}

type PermissionSpec struct {
	Name    string
	GoName  string
	Actions []string
}

func NormalizePermission(input PermissionInput) (PermissionSpec, error) {
	if !resourceNamePattern.MatchString(input.Name) {
		return PermissionSpec{}, fmt.Errorf("invalid permission resource name %q", input.Name)
	}
	if len(input.Actions) == 0 {
		return PermissionSpec{}, fmt.Errorf("permission resource %q requires at least one action", input.Name)
	}
	spec := PermissionSpec{Name: input.Name, GoName: pascal(input.Name)}
	seen := make(map[string]struct{}, len(input.Actions))
	for _, action := range input.Actions {
		if _, ok := supportedPermissionActions[action]; !ok {
			return PermissionSpec{}, fmt.Errorf("unsupported permission action %q", action)
		}
		if _, exists := seen[action]; exists {
			return PermissionSpec{}, fmt.Errorf("duplicate permission action %q", action)
		}
		seen[action] = struct{}{}
		spec.Actions = append(spec.Actions, action)
	}
	return spec, nil
}

func RenderPermission(spec PermissionSpec) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("app", "generated", "permissions", spec.Name))
	var constants strings.Builder
	var all strings.Builder
	for index, action := range spec.Actions {
		constant := spec.GoName + pascal(action)
		permission := "admin." + spec.Name + "." + action
		fmt.Fprintf(&constants, "\t%s = %q\n", constant, permission)
		if index > 0 {
			all.WriteString(", ")
		}
		all.WriteString(constant)
	}
	source := fmt.Sprintf(`// Code generated by admin:make-permission. DO NOT EDIT.
package permissions

const (
%s)

var All = []string{%s}
`, constants.String(), all.String())
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("format permissions: %w", err)
	}
	readme := fmt.Sprintf(`# %s permissions

This permission set was generated by `+"`admin:make-permission`"+`.

Generated permissions:

%s

The generator only creates code. Review the names, then add them to the database and role assignments manually through the approved RBAC workflow. It does not write permission rows or bind roles.
`, spec.Name, permissionList(spec))
	return []Artifact{
		{Path: filepath.ToSlash(filepath.Join(base, "permissions.go")), Content: formatted},
		{Path: filepath.ToSlash(filepath.Join(base, "README.md")), Content: []byte(readme)},
	}, nil
}

func permissionList(spec PermissionSpec) string {
	var result strings.Builder
	for _, action := range spec.Actions {
		fmt.Fprintf(&result, "- `admin.%s.%s`\n", spec.Name, action)
	}
	return result.String()
}
