package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
)

type Artifact struct {
	Path           string
	Content        []byte
	AllowOverwrite bool
}

func Render(spec Spec, migrationTimestamp string) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("app", "modules", spec.Name, "resource"))
	packageName := strings.ReplaceAll(spec.Name, "-", "_")

	files := []struct {
		name string
		body string
	}{
		{"manifest.go", manifestSource(spec, packageName)},
		{"model.go", modelSource(spec, packageName)},
		{"request.go", plainSource(packageName, "Request")},
		{"repository.go", plainSource(packageName, "Repository")},
		{"service.go", plainSource(packageName, "Service")},
		{"controller.go", plainSource(packageName, "Controller")},
		{"routes.go", plainSource(packageName, "Routes")},
		{"permissions.go", permissionsSource(spec, packageName)},
		{"manifest_test.go", manifestTestSource(spec, packageName)},
	}

	artifacts := make([]Artifact, 0, len(files)+1)
	for _, file := range files {
		content, err := format.Source([]byte(file.body))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", file.name, err)
		}
		artifacts = append(artifacts, Artifact{Path: filepath.ToSlash(filepath.Join(base, file.name)), Content: content})
	}

	migration := migrationSource(spec, packageName)
	migrationContent, err := format.Source([]byte(migration))
	if err != nil {
		return nil, fmt.Errorf("format migration: %w", err)
	}
	artifacts = append(artifacts, Artifact{
		Path:    filepath.ToSlash(filepath.Join("database", "migrations", migrationTimestamp+"_create_"+spec.Name+"_table.go")),
		Content: migrationContent,
	})
	artifacts = append(artifacts, Artifact{
		Path:    filepath.ToSlash(filepath.Join(base, "README.md")),
		Content: []byte(resourceReadmeSource(spec)),
	})
	return artifacts, nil
}

func resourceReadmeSource(spec Spec) string {
	return fmt.Sprintf(`# %s resource

This resource was generated by `+"`admin:make-resource`"+`.

## Generated files

- `+"`manifest.go`"+`: Resource metadata and fields.
- `+"`model.go`"+`: ORM model skeleton.
- `+"`request.go`"+`: request boundary.
- `+"`repository.go`"+`: persistence boundary.
- `+"`service.go`"+`: business-service boundary.
- `+"`controller.go`"+`: HTTP boundary.
- `+"`routes.go`"+`: route boundary.
- `+"`permissions.go`"+`: permission boundary.
- `+"`manifest_test.go`"+`: generated manifest test.
- `+"`backend/database/migrations/*_create_%s_table.go`"+`: migration proposal.
- `+"`app/modules/%s/permissions/`"+`: generated permission constants.
- `+"`app/modules/%s/menu/`"+`: generated menu metadata.
- `+"`admin/src/modules/%s/`"+`: frontend metadata, routes and page skeletons.
- `+"`admin/src/modules/%s/api.ts`"+`: list/show/create/update/delete API contract.

## Automatic activation

1. Review the generated files and implement the business behavior.
2. The generator updates the generated backend Registry and frontend discovery files automatically.
3. Review the generated form fields, shared page behavior, and authorization metadata.
4. Review the migration file and execute it manually only after approval.
5. Add the generated migration type to `+"`backend/bootstrap/migrations.go`"+`, then run `+"`go run . artisan migrate`"+`.
6. Assign the generated permissions to an appropriate role from the RBAC page or API.

For an `+"`own`"+` resource, generate an integer owner field with `+"`--owner-field`"+` and use `+"`--scope=own`"+`. Role assignments can then select the Own data only option; the backend sets the owner from the authenticated user and ignores client-supplied owner IDs.

The generator does not modify manually maintained runtime files and does not execute migrations.

## Verification

From `+"`backend/`"+` run:

`+"```text"+`
go test ./...
`+"```"+`
`, spec.Name, spec.Name, spec.Name, spec.Name, spec.Name, spec.Name)
}

func manifestSource(spec Spec, packageName string) string {
	var fields strings.Builder
	var columns strings.Builder
	var actions strings.Builder
	for _, field := range spec.Fields {
		label := humanize(field.Name)
		if len(field.Options) == 0 {
			if field.Required {
				fmt.Fprintf(&fields, "\t\t{Name: %q, Label: %q, Type: %q, Required: true},\n", field.Name, label, field.Type)
			} else {
				fmt.Fprintf(&fields, "\t\t{Name: %q, Label: %q, Type: %q},\n", field.Name, label, field.Type)
			}
		} else {
			var values strings.Builder
			for _, option := range field.Options {
				fmt.Fprintf(&values, "{Value: %q, Label: %q}, ", option.Value, option.Label)
			}
			fmt.Fprintf(&fields, "\t\t{Name: %q, Label: %q, Type: %q, Required: %t, Options: []resource.Option{%s}},\n", field.Name, label, field.Type, field.Required, values.String())
		}
		fmt.Fprintf(&columns, "\t\t{Name: %q, Label: %q, Sortable: true},\n", field.Name, label)
	}
	for _, action := range spec.Actions {
		fmt.Fprintf(&actions, "\t\t{Name: %q, Label: %q, Permission: %q},\n", action, humanize(action), "admin."+spec.Name+"."+action)
	}
	scopeMetadata := ""
	if spec.DataScope == "own" {
		scopeMetadata = fmt.Sprintf("\t\tDataScope: resource.DataScopeOwn, OwnerField: %q,\n", spec.OwnerField)
	}
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

import "goravel/app/core/resource"

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: %q, Label: %q, Route: %q, Table: %q, Permissions: []string{%q},
%s
		Fields: []resource.Field{
%s		},
		Columns: []resource.Column{
%s		},
		Actions: []resource.Action{
%s		},
	}
}
`, packageName, spec.Name, spec.Label, spec.Route, spec.Name, spec.Permission, scopeMetadata, fields.String(), columns.String(), actions.String())
}

func modelSource(spec Spec, packageName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

import "github.com/goravel/framework/database/orm"

type %s struct {
	orm.Model
%s}
`, packageName, spec.GoName, modelFields(spec))
}

func modelFields(spec Spec) string {
	var result strings.Builder
	for _, field := range spec.Fields {
		goType := "string"
		switch field.Type {
		case "integer":
			goType = "int"
		case "boolean":
			goType = "bool"
		}
		fmt.Fprintf(&result, "\t%s %s `json:%q`\n", field.GoName, goType, field.Name)
	}
	return result.String()
}

func plainSource(packageName, typeName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

// %s is an integration boundary for the generated resource.
type %s struct{}
`, packageName, typeName, typeName)
}

func permissionsSource(spec Spec, packageName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

const ViewPermission = %q
`, packageName, spec.Permission)
}

func manifestTestSource(spec Spec, packageName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != %q || manifest.Route != %q {
		t.Fatalf("unexpected manifest: %%+v", manifest)
	}
}
`, packageName, spec.Name, spec.Route)
}

func migrationSource(spec Spec, packageName string) string {
	var columns strings.Builder
	for _, field := range spec.Fields {
		method := "String"
		switch field.Type {
		case "integer":
			method = "Integer"
		case "boolean":
			method = "Boolean"
		}
		fmt.Fprintf(&columns, "\t\ttable.%s(%q)\n", method, field.Name)
	}
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
	"goravel/app/models"
)

type M%sCreate%sTable struct{}

func (m *M%sCreate%sTable) Signature() string {
	return "create_%s_table"
}

func (m *M%sCreate%sTable) Up() error {
	if err := facades.Schema().Create("%s", func(table schema.Blueprint) {
		table.ID()
%s		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	}); err != nil {
		return err
	}
	for _, permission := range []models.Permission{
		%s	} {
		exists, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission.Name).Exists()
		if err != nil {
			return err
		}
		if !exists {
			if err := facades.Orm().Query().Create(&permission); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *M%sCreate%sTable) Down() error {
	for _, permission := range []string{
%s	} {
		if _, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission).Delete(); err != nil {
			return err
		}
	}
	return facades.Schema().DropIfExists("%s")
}
`, packageName, spec.GoName, packageName, spec.GoName, spec.Name, packageName, spec.GoName, spec.Name, columns.String(), migrationPermissions(spec), packageName, spec.GoName, migrationPermissionLiterals(spec), spec.Name)
}

func migrationPermissions(spec Spec) string {
	var result strings.Builder
	for _, permission := range migrationPermissionNames(spec) {
		fmt.Fprintf(&result, "\t\t{Name: %q, DisplayName: %q},\n", permission, humanize(strings.TrimPrefix(permission, "admin.")))
	}
	return result.String()
}

func migrationPermissionNames(spec Spec) []string {
	permissions := make([]string, 0, len(spec.Actions)+1)
	seen := make(map[string]struct{}, len(spec.Actions)+1)
	appendPermission := func(permission string) {
		if _, exists := seen[permission]; exists {
			return
		}
		seen[permission] = struct{}{}
		permissions = append(permissions, permission)
	}
	appendPermission(spec.Permission)
	for _, action := range spec.Actions {
		appendPermission("admin." + spec.Name + "." + action)
	}
	return permissions
}

func migrationPermissionLiterals(spec Spec) string {
	var result strings.Builder
	for _, permission := range migrationPermissionNames(spec) {
		fmt.Fprintf(&result, "\t\t%q,\n", permission)
	}
	return result.String()
}
