package generator

import (
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
)

type Artifact struct {
	Path    string
	Content []byte
}

func Render(spec Spec, migrationTimestamp string) ([]Artifact, error) {
	base := filepath.ToSlash(filepath.Join("app", "generated", "resources", spec.Name))
	packageName := strings.ReplaceAll(spec.Name, "-", "_")

	files := []struct {
		name string
		body string
	}{
		{"manifest.go", manifestSource(spec, packageName)},
		{"model.go", modelSource(spec, packageName)},
		{"request.go", plainSource(packageName, "Request")},
		{"repository.go", plainSource(packageName, "Repository")},
		{"service.go", plainSource(packageName, "Service")},
		{"controller.go", plainSource(packageName, "Controller")},
		{"routes.go", plainSource(packageName, "Routes")},
		{"permissions.go", permissionsSource(spec, packageName)},
		{"manifest_test.go", manifestTestSource(spec, packageName)},
	}

	artifacts := make([]Artifact, 0, len(files)+1)
	for _, file := range files {
		content, err := format.Source([]byte(file.body))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", file.name, err)
		}
		artifacts = append(artifacts, Artifact{Path: filepath.ToSlash(filepath.Join(base, file.name)), Content: content})
	}

	migration := migrationSource(spec, packageName)
	migrationContent, err := format.Source([]byte(migration))
	if err != nil {
		return nil, fmt.Errorf("format migration: %w", err)
	}
	artifacts = append(artifacts, Artifact{
		Path:    filepath.ToSlash(filepath.Join("database", "migrations", migrationTimestamp+"_create_"+spec.Name+"_table.go")),
		Content: migrationContent,
	})
	artifacts = append(artifacts, Artifact{
		Path:    filepath.ToSlash(filepath.Join(base, "README.md")),
		Content: []byte(resourceReadmeSource(spec)),
	})
	return artifacts, nil
}

func resourceReadmeSource(spec Spec) string {
	return fmt.Sprintf(`# %s resource

This resource was generated by `+"`admin:make-resource`"+`.

## Generated files

- `+"`manifest.go`"+`: Resource metadata and fields.
- `+"`model.go`"+`: ORM model skeleton.
- `+"`request.go`"+`: request boundary.
- `+"`repository.go`"+`: persistence boundary.
- `+"`service.go`"+`: business-service boundary.
- `+"`controller.go`"+`: HTTP boundary.
- `+"`routes.go`"+`: route boundary.
- `+"`permissions.go`"+`: permission boundary.
- `+"`manifest_test.go`"+`: generated manifest test.
- `+"`backend/database/migrations/*_create_%s_table.go`"+`: migration proposal.
- `+"`app/generated/permissions/%s/`"+`: generated permission constants.
- `+"`app/generated/menus/%s/`"+`: generated menu metadata.
- `+"`admin/src/generated/resources/%s/`"+`: frontend metadata, routes and page skeletons.

## Manual activation

1. Review the generated files and implement the business behavior.
2. Register `+"`Manifest()`"+` in the Resource Registry manually.
3. Register the generated frontend routes, menu entry and permissions manually after authorization review.
4. Connect the generated form scaffold to the approved form/API contract.
5. Review the migration file and execute it manually only after approval.

The generator does not register runtime behavior and does not execute migrations.

## Verification

From `+"`backend/`"+` run:

`+"```text"+`
go test ./...
`+"```"+`
`, spec.Name, spec.Name, spec.Name, spec.Name, spec.Name)
}

func manifestSource(spec Spec, packageName string) string {
	var fields strings.Builder
	var columns strings.Builder
	for _, field := range spec.Fields {
		label := humanize(field.Name)
		fmt.Fprintf(&fields, "\t\t{Name: %q, Label: %q, Type: %q},\n", field.Name, label, field.Type)
		fmt.Fprintf(&columns, "\t\t{Name: %q, Label: %q, Sortable: true},\n", field.Name, label)
	}
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

import "goravel/app/resource"

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: %q, Label: %q, Route: %q, Permissions: []string{%q},
		Fields: []resource.Field{
%s		},
		Columns: []resource.Column{
%s		},
	}
}
`, packageName, spec.Name, spec.Label, spec.Route, spec.Permission, fields.String(), columns.String())
}

func modelSource(spec Spec, packageName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

import "github.com/goravel/framework/database/orm"

type %s struct {
	orm.Model
%s}
`, packageName, spec.GoName, modelFields(spec))
}

func modelFields(spec Spec) string {
	var result strings.Builder
	for _, field := range spec.Fields {
		goType := "string"
		switch field.Type {
		case "integer":
			goType = "int"
		case "boolean":
			goType = "bool"
		}
		fmt.Fprintf(&result, "\t%s %s `json:%q`\n", field.GoName, goType, field.Name)
	}
	return result.String()
}

func plainSource(packageName, typeName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

// %s is an integration boundary for the generated resource.
type %s struct{}
`, packageName, typeName, typeName)
}

func permissionsSource(spec Spec, packageName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

const ViewPermission = %q
`, packageName, spec.Permission)
}

func manifestTestSource(spec Spec, packageName string) string {
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package %s

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != %q || manifest.Route != %q {
		t.Fatalf("unexpected manifest: %%+v", manifest)
	}
}
`, packageName, spec.Name, spec.Route)
}

func migrationSource(spec Spec, packageName string) string {
	var columns strings.Builder
	for _, field := range spec.Fields {
		method := "String"
		switch field.Type {
		case "integer":
			method = "Integer"
		case "boolean":
			method = "Boolean"
		}
		fmt.Fprintf(&columns, "\t\ttable.%s(%q)\n", method, field.Name)
	}
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
)

type M%sCreate%sTable struct{}

func (m *M%sCreate%sTable) Signature() string {
	return "create_%s_table"
}

func (m *M%sCreate%sTable) Up() error {
	return facades.Schema().Create("%s", func(table schema.Blueprint) {
		table.ID()
%s		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	})
}

func (m *M%sCreate%sTable) Down() error {
	return facades.Schema().DropIfExists("%s")
}
`, packageName, spec.GoName, packageName, spec.GoName, spec.Name, packageName, spec.GoName, spec.Name, columns.String(), packageName, spec.GoName, spec.Name)
}
