package generator

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type generatedResource struct {
	Name    string
	GoName  string
	Package string
}

// RenderRuntimeRegistration updates only generator-owned discovery files. The
// application router, sidebar, and registry consume these files automatically.
func RenderRuntimeRegistration(root string, spec Spec) ([]Artifact, error) {
	resources := discoverGeneratedResources(filepath.Join(root, "app", "modules"), spec.Name, "resource", "manifest.go")
	backend, err := generatedBackendRegistry(resources)
	if err != nil {
		return nil, err
	}
	frontendRoot := resolveFrontendRoot(root)
	frontendModulesRoot := filepath.Join(frontendRoot, "src", "modules")
	if frontendRoot == root {
		frontendModulesRoot = filepath.Join(root, "admin", "src", "modules")
	}
	frontendResources := discoverGeneratedResources(frontendModulesRoot, spec.Name, "", "resource.ts")
	frontend := generatedFrontendRegistry(frontendResources)
	return []Artifact{
		{Path: "app/modules/admin/registry/generated_resources.go", Content: backend, AllowOverwrite: true},
		{Path: "admin/src/core/resource/generated.ts", Content: []byte(frontend), AllowOverwrite: true},
	}, nil
}

func discoverGeneratedResources(root, current, nested, marker string) []generatedResource {
	seen := map[string]bool{}
	entries, _ := os.ReadDir(root)
	resources := make([]generatedResource, 0)
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "admin" {
			continue
		}
		name := entry.Name()
		path := filepath.Join(root, name, marker)
		if nested != "" {
			path = filepath.Join(root, name, nested, marker)
		}
		if _, err := os.Stat(path); err != nil {
			continue
		}
		seen[name] = true
		resources = append(resources, generatedResource{Name: name, GoName: pascal(name), Package: strings.ReplaceAll(name, "-", "_")})
	}
	if !seen[current] {
		resources = append(resources, generatedResource{Name: current, GoName: pascal(current), Package: strings.ReplaceAll(current, "-", "_")})
	}
	sort.Slice(resources, func(i, j int) bool { return resources[i].Name < resources[j].Name })
	return resources
}

func generatedBackendRegistry(resources []generatedResource) ([]byte, error) {
	var imports strings.Builder
	var registrations strings.Builder
	for _, item := range resources {
		alias := item.Package + "resource"
		fmt.Fprintf(&imports, "\t%s %q\n", alias, "goravel/app/modules/"+item.Name+"/resource")
		fmt.Fprintf(&registrations, "\t_ = registry.Register(%s.Manifest())\n", alias)
	}
	source := fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
package registry

import (
	"goravel/app/core/resource"
%s)

func registerGenerated(registry *resource.Registry) {
%s}
`, imports.String(), registrations.String())
	return format.Source([]byte(source))
}

func generatedFrontendRegistry(resources []generatedResource) string {
	var imports strings.Builder
	var definitions strings.Builder
	var routes strings.Builder
	for _, item := range resources {
		alias := item.Package + "Resource"
		fmt.Fprintf(&imports, "import { resourceDefinition as %s } from '@/modules/%s/resource'\n", alias, item.Name)
		fmt.Fprintf(&imports, "import %sListPage from '@/modules/%s/pages/%sListPage.vue'\n", item.GoName, item.Name, item.GoName)
		fmt.Fprintf(&imports, "import %sFormPage from '@/modules/%s/pages/%sFormPage.vue'\n", item.GoName, item.Name, item.GoName)
		fmt.Fprintf(&imports, "import %sDetailPage from '@/modules/%s/pages/%sDetailPage.vue'\n", item.GoName, item.Name, item.GoName)
		fmt.Fprintf(&definitions, "  %s,\n", alias)
		fmt.Fprintf(&routes, "  { path: %s.route, name: %q, meta: { permission: %s.permission }, component: %sListPage },\n", alias, item.Name+"-resource-list", alias, item.GoName)
		fmt.Fprintf(&routes, "  { path: %s.route + '/new', name: %q, meta: { permission: %s.permission }, component: %sFormPage },\n", alias, item.Name+"-resource-create", alias, item.GoName)
		fmt.Fprintf(&routes, "  { path: %s.route + '/:id/edit', name: %q, meta: { permission: %s.permission }, component: %sFormPage },\n", alias, item.Name+"-resource-edit", alias, item.GoName)
		fmt.Fprintf(&routes, "  { path: %s.route + '/:id', name: %q, meta: { permission: %s.permission }, component: %sDetailPage },\n", alias, item.Name+"-resource-detail", alias, item.GoName)
	}
	return fmt.Sprintf(`// Code generated by admin:make-resource. DO NOT EDIT.
import type { RouteRecordRaw } from 'vue-router'
%s
export interface GeneratedResourceDefinition {
  name: string
  label: string
  route: string
  permission: string
  icon: string
}

export const generatedResourceDefinitions = [
%s] as const

export const generatedResourceRoutes: RouteRecordRaw[] = [
%s]
`, imports.String(), definitions.String(), routes.String())
}
