// Code generated by admin:make-module. DO NOT EDIT.
package billing_test

import "testing"

func TestModuleBoundaryExists(t *testing.T) {
	t.Skip("implement module behavior after manual runtime registration")
}
