// Code generated by admin:make-resource. DO NOT EDIT.
import { generatedApi } from '@/generated/api';

export type ResourceRecord = Record<string, unknown>;
export type ResourceList<T = ResourceRecord> = { data: T[]; meta?: Record<string, unknown> };

export const resourceApi = {
  list(query: URLSearchParams, token: string) {
    return generatedApi.resourceList<ResourceRecord>("announcements", query, token) as unknown as Promise<ResourceList>;
  },
  show(id: string | number, token: string) {
    return generatedApi.resourceShow<ResourceRecord>("announcements", id, token);
  },
  create(payload: ResourceRecord, token: string) {
    return generatedApi.resourceCreate<ResourceRecord>("announcements", payload, token);
  },
  update(id: string | number, payload: ResourceRecord, token: string) {
    return generatedApi.resourceUpdate<ResourceRecord>("announcements", id, payload, token);
  },
  remove(id: string | number, token: string) {
    return generatedApi.resourceDelete("announcements", id, token);
  },
};
