// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: "announcements",
  label: "Announcements",
  route: "/announcements",
  permission: "admin.announcements.view",
  icon: "box",
  actions: ["view", "create", "update", "delete"],
  fields: [{ name: "title", label: "Title", type: "text", required: true }, { name: "status", label: "Status", type: "select", required: true, options: [{ value: "draft", label: "Draft" }, { value: "published", label: "Published" }] }],
} as const;
