import { expect, test } from '@playwright/test'

test('users support create, reload, edit, and delete through the admin', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('邮箱').fill(process.env.AUTH_BOOTSTRAP_EMAIL ?? 'admin@example.com')
  await page.getByLabel('密码', { exact: true }).fill(process.env.AUTH_BOOTSTRAP_PASSWORD ?? 'test-only-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/dashboard/)
  await page.goto('/admin/resources/users')
  await page.getByRole('button', { name: '新建', exact: true }).click()
  const name = `E2E 用户 ${Date.now()}`
  const email = `e2e-${Date.now()}@example.com`
  await page.getByLabel('姓名', { exact: true }).fill(name)
  await page.getByLabel('邮箱', { exact: true }).fill(email)
  await page.getByLabel('启用', { exact: true }).check()
  await page.getByLabel('角色 ID', { exact: true }).fill('platform-admin')
  await page.getByRole('button', { name: '创建', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/resources\/users\/users-/)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByText(email, { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(page.getByLabel('姓名', { exact: true })).toHaveValue(name)
  await expect(page.getByLabel('邮箱', { exact: true })).toHaveValue(email)
  await expect(page.getByLabel('启用', { exact: true })).toBeChecked()
  await expect(page.getByLabel('角色 ID', { exact: true })).toHaveValue('platform-admin')
  await page.getByLabel('姓名', { exact: true }).fill(`${name} updated`)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page).not.toHaveURL(/\/edit$/)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByText(`${name} updated`, { exact: true }).last()).toBeVisible()
  await expect(page.getByText(email, { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '确认删除' }).click()
  await expect(page).toHaveURL(/\/admin\/resources\/users$/)
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('cell', { name: email, exact: true })).toHaveCount(0)
})
