// Code generated by admin:make-resource. DO NOT EDIT.
package announcements

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != "announcements" || manifest.Route != "/admin/announcements" {
		t.Fatalf("unexpected manifest: %+v", manifest)
	}
}
