// Code generated by admin:make-resource. DO NOT EDIT.
package announcements

import "goravel/app/core/resource"

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: "announcements", Label: "Announcements", Route: "/admin/announcements", Table: "announcements", Permissions: []string{"admin.announcements.view"}, DataScope: resource.DataScopeAll, Navigation: resource.Navigation{Group: "business", Order: 100},
		Fields: []resource.Field{
			{Name: "title", Label: "Title", Type: "text", Required: true},
			{Name: "status", Label: "Status", Type: "select", Required: true, Options: []resource.Option{{Value: "draft", Label: "Draft"}, {Value: "published", Label: "Published"}}},
		},
		Columns: []resource.Column{
			{Name: "title", Label: "Title", Sortable: true},
			{Name: "status", Label: "Status", Sortable: true},
		},
		Actions: []resource.Action{
			{Name: "view", Label: "View", Permission: "admin.announcements.view"},
			{Name: "create", Label: "Create", Permission: "admin.announcements.create"},
			{Name: "update", Label: "Update", Permission: "admin.announcements.update"},
			{Name: "delete", Label: "Delete", Permission: "admin.announcements.delete"},
		},
	}
}
