// Code generated by admin:make-resource. DO NOT EDIT.
package announcements

import "github.com/goravel/framework/database/orm"

type Announcements struct {
	orm.Model
	Title  string `json:"title"`
	Status string `json:"status"`
}
