// Code generated by admin:make-resource. DO NOT EDIT.
package departments

import "testing"

func TestManifestHasResourceIdentity(t *testing.T) {
	manifest := Manifest()
	if manifest.Name != "departments" || manifest.Route != "/admin/departments" {
		t.Fatalf("unexpected manifest: %+v", manifest)
	}
}
