// Code generated by admin:make-resource. DO NOT EDIT.
package departments

import "goravel/app/core/resource"

func Manifest() resource.Manifest {
	return resource.Manifest{
		Name: "departments", Label: "Departments", Route: "/admin/departments", Table: "departments", Permissions: []string{"admin.departments.view"}, Navigation: resource.Navigation{Group: "business", Order: 100},

		Fields: []resource.Field{
			{Name: "name", Label: "Name", Type: "text", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "code", Label: "Code", Type: "text", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true},
			{Name: "status", Label: "Status", Type: "select", Required: true, Visible: true, Readable: true, Writable: true, Sensitive: false, PolicyConfigured: true, Options: []resource.Option{{Value: "active", Label: "Active"}, {Value: "disabled", Label: "Disabled"}}},
		},
		Columns: []resource.Column{
			{Name: "name", Label: "Name", Sortable: true},
			{Name: "code", Label: "Code", Sortable: true},
			{Name: "status", Label: "Status", Sortable: true},
		},
		Actions: []resource.Action{
			{Name: "view", Label: "View", Kind: "", Permission: "admin.departments.view", Batch: false, Payload: ""},
			{Name: "create", Label: "Create", Kind: "", Permission: "admin.departments.create", Batch: false, Payload: ""},
			{Name: "update", Label: "Update", Kind: "", Permission: "admin.departments.update", Batch: false, Payload: ""},
			{Name: "delete", Label: "Delete", Kind: "", Permission: "admin.departments.delete", Batch: false, Payload: ""},
		},
		Relations:  []resource.Relation{},
		FormGroups: []resource.FormGroup{},
		Details:    []resource.DetailSection{},
	}
}
