// Code generated by admin:make-resource. DO NOT EDIT.
package permissions

const (
	AnnouncementsView   = "admin.announcements.view"
	AnnouncementsCreate = "admin.announcements.create"
	AnnouncementsUpdate = "admin.announcements.update"
	AnnouncementsDelete = "admin.announcements.delete"
)

var All = []string{AnnouncementsView, AnnouncementsCreate, AnnouncementsUpdate, AnnouncementsDelete}
