package generator

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"goravel/app/core/openapi"
)

// APIOptions controls the repository-relative outputs produced by admin-gen api.
type APIOptions struct {
	RootDir   string
	Output    string
	SchemaDir string
	ClientDir string
}

// GenerateAPI writes the OpenAPI contract, split JSON schemas, and the admin's
// TypeScript API client from the single Go OpenAPI document.
func GenerateAPI(options APIOptions) error {
	root := options.RootDir
	if root == "" {
		root = "."
	}
	output := resolveAPIPath(root, options.Output, filepath.FromSlash("contracts/openapi/openapi.json"))
	schemaDir := resolveAPIPath(root, options.SchemaDir, filepath.FromSlash("contracts/schemas"))
	clientDir := resolveAPIPath(root, options.ClientDir, filepath.FromSlash("admin/src/generated/api"))

	document := openapi.BuildDocument()
	if err := openapi.WriteJSON(output, document); err != nil {
		return fmt.Errorf("write OpenAPI document: %w", err)
	}
	for _, name := range sortedKeys(openapi.SchemaDocuments()) {
		if err := openapi.WriteJSON(filepath.Join(schemaDir, name+".json"), openapi.SchemaDocuments()[name]); err != nil {
			return fmt.Errorf("write schema %s: %w", name, err)
		}
	}
	if err := os.MkdirAll(clientDir, 0o755); err != nil {
		return fmt.Errorf("create TypeScript client directory: %w", err)
	}
	files := map[string]string{
		"models.ts": renderAPIModels(document),
		"client.ts": renderAPIClient(document),
		"index.ts":  "// This file is generated by admin-gen api. Do not edit by hand.\nexport * from './models'\nexport * from './client'\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(clientDir, name), []byte(content), 0o644); err != nil {
			return fmt.Errorf("write TypeScript client %s: %w", name, err)
		}
	}
	return nil
}

func resolveAPIPath(root, value, fallback string) string {
	if value == "" {
		value = fallback
	}
	if filepath.IsAbs(value) {
		return value
	}
	return filepath.Join(root, value)
}

func sortedKeys(values map[string]any) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func apiPaths(document map[string]any) map[string]any {
	paths, _ := document["paths"].(map[string]any)
	return paths
}

func apiResources(document map[string]any) []string {
	var resources []string
	for path := range apiPaths(document) {
		if strings.HasPrefix(path, "/api/resources/") && !strings.Contains(path, "/{id}") && !strings.HasSuffix(path, "/bulk-delete") {
			resources = append(resources, strings.TrimPrefix(path, "/api/resources/"))
		}
	}
	sort.Strings(resources)
	return resources
}

func hasAPIPath(document map[string]any, path string) bool {
	_, ok := apiPaths(document)[path]
	return ok
}

func apiPascal(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '-' || r == '_' })
	for i, part := range parts {
		if part != "" {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func apiSingular(resource string) string {
	if resource == "demo" {
		return "Demo"
	}
	return apiPascal(strings.TrimSuffix(resource, "s"))
}

func apiModelName(resource string) string { return apiSingular(resource) + "Resource" }

func apiPluralMethod(resource string) string {
	if resource == "demo" {
		return "DemoResources"
	}
	return apiPascal(resource)
}

func apiOperationMethod(resource, action string) string {
	if action == "list" || action == "bulkDelete" {
		prefix := "list"
		if action == "bulkDelete" {
			prefix = "bulkDelete"
		}
		return prefix + apiPluralMethod(resource)
	}
	if resource == "demo" {
		return action + apiSingular(resource) + "Resource"
	}
	return action + apiSingular(resource)
}

func apiSchemas(document map[string]any) map[string]any {
	components, _ := document["components"].(map[string]any)
	schemas, _ := components["schemas"].(map[string]any)
	return schemas
}

func apiType(schema any) string {
	value, _ := schema.(map[string]any)
	if ref, ok := value["$ref"].(string); ok {
		return ref[strings.LastIndex(ref, "/")+1:]
	}
	if enum, ok := value["enum"].([]any); ok {
		items := make([]string, len(enum))
		for i, item := range enum {
			encoded, _ := json.Marshal(item)
			items[i] = string(encoded)
		}
		return strings.Join(items, " | ")
	}
	if value["type"] == "array" {
		return apiType(value["items"]) + "[]"
	}
	switch value["type"] {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "object":
		return "Record<string, unknown>"
	}
	return "unknown"
}

func apiInterface(resource string, schemas map[string]any) string {
	name := apiModelName(resource)
	schema, _ := schemas[name].(map[string]any)
	properties, _ := schema["properties"].(map[string]any)
	required := map[string]bool{}
	if values, ok := schema["required"].([]any); ok {
		for _, value := range values {
			if key, ok := value.(string); ok {
				required[key] = true
			}
		}
	}
	lines := make([]string, 0, len(properties))
	for _, key := range sortedKeys(properties) {
		lines = append(lines, "  "+key+map[bool]string{true: "", false: "?"}[required[key]]+": "+apiType(properties[key]))
	}
	return "export interface " + name + " {\n" + strings.Join(lines, "\n") + "\n}"
}

func renderAPIModels(document map[string]any) string {
	resources := apiResources(document)
	if hasAPIPath(document, "/api/settings") {
		resources = append(resources, "setting")
	}
	if hasAPIPath(document, "/api/media") {
		resources = append(resources, "media")
	}
	if hasAPIPath(document, "/api/audit") {
		resources = append(resources, "audit")
	}
	if hasAPIPath(document, "/api/extensions") {
		resources = append(resources, "extension")
	}
	sort.Strings(resources)
	interfaces := make([]string, 0, len(resources))
	schemas := apiSchemas(document)
	for _, resource := range resources {
		interfaces = append(interfaces, apiInterface(resource, schemas))
	}
	return "/* eslint-disable */\n// This file is generated by admin-gen api. Do not edit by hand.\n\n" +
		"export interface ResourceListQuery {\n  page?: number\n  perPage?: number\n  search?: string\n  namespace?: string\n  filters?: Record<string, string>\n  sort?: { field: string; direction: 'asc' | 'desc' }\n}\n\n" + "export interface ResourcePagination {\n  page: number\n  per_page: number\n  total: number\n  total_pages: number\n}\n\nexport interface ResourceEnvelope<T> {\n  data: T\n  meta?: { request_id?: string; pagination?: ResourcePagination }\n}\n\n" + strings.Join(interfaces, "\n\n") + "\n"
}

func renderAPIClient(document map[string]any) string {
	resources := apiResources(document)
	imports := []string{}
	for _, resource := range resources {
		imports = append(imports, apiModelName(resource))
	}
	for _, path := range []struct{ path, resource string }{{"/api/settings", "setting"}, {"/api/media", "media"}, {"/api/audit", "audit"}, {"/api/extensions", "extension"}} {
		if hasAPIPath(document, path.path) {
			imports = append(imports, apiModelName(path.resource))
		}
	}
	methods, implementations := []string{}, []string{}
	for _, resource := range resources {
		model, base := apiModelName(resource), "/api/resources/"+resource
		list, get, create, update, deleteMethod, bulk := apiOperationMethod(resource, "list"), apiOperationMethod(resource, "get"), apiOperationMethod(resource, "create"), apiOperationMethod(resource, "update"), apiOperationMethod(resource, "delete"), apiOperationMethod(resource, "bulkDelete")
		methods = append(methods, "  "+list+"(query?: ResourceListQuery): Promise<ResourceEnvelope<"+model+"[]>>", "  "+get+"(id: string): Promise<ResourceEnvelope<"+model+">>", "  "+create+"(input: "+model+"): Promise<ResourceEnvelope<"+model+">>", "  "+update+"(id: string, input: Partial<"+model+">): Promise<ResourceEnvelope<"+model+">>", "  "+deleteMethod+"(id: string): Promise<ResourceEnvelope<{ deleted: boolean }>>", "  "+bulk+"(input: { ids: string[] }): Promise<ResourceEnvelope<{ deleted: boolean }>>")
		implementations = append(implementations, "    "+list+": (query) => client.request<ResourceEnvelope<"+model+"[]>>(withQuery('"+base+"', query)),", "    "+get+": (id) => client.request<ResourceEnvelope<"+model+">>(itemPath('"+base+"', id)),", "    "+create+": (input) => client.request<ResourceEnvelope<"+model+">>('"+base+"', jsonOptions('POST', input)),", "    "+update+": (id, input) => client.request<ResourceEnvelope<"+model+">>(itemPath('"+base+"', id), jsonOptions('PUT', input)),", "    "+deleteMethod+": (id) => client.request<ResourceEnvelope<{ deleted: boolean }>>(itemPath('"+base+"', id), { method: 'DELETE' }),", "    "+bulk+": (input) => client.request<ResourceEnvelope<{ deleted: boolean }>>('"+base+"/bulk-delete', jsonOptions('POST', input)),")
	}
	if hasAPIPath(document, "/api/settings") {
		methods = append(methods, "  listSettings(query?: Pick<ResourceListQuery, 'namespace'>): Promise<ResourceEnvelope<SettingResource[]>>", "  upsertSetting(input: SettingResource): Promise<ResourceEnvelope<SettingResource>>", "  updateSetting(namespace: string, key: string, input: Partial<SettingResource>): Promise<ResourceEnvelope<SettingResource>>", "  deleteSetting(namespace: string, key: string): Promise<ResourceEnvelope<{ deleted: boolean }>>")
		implementations = append(implementations, "    listSettings: (query) => client.request<ResourceEnvelope<SettingResource[]>>(withQuery('/api/settings', query)),", "    upsertSetting: (input) => client.request<ResourceEnvelope<SettingResource>>('/api/settings', jsonOptions('POST', input)),", "    updateSetting: (namespace, key, input) => client.request<ResourceEnvelope<SettingResource>>('/api/settings/' + encodeURIComponent(namespace) + '/' + encodeURIComponent(key), jsonOptions('PUT', input)),", "    deleteSetting: (namespace, key) => client.request<ResourceEnvelope<{ deleted: boolean }>>('/api/settings/' + encodeURIComponent(namespace) + '/' + encodeURIComponent(key), { method: 'DELETE' }),")
	}
	if hasAPIPath(document, "/api/media") {
		methods = append(methods, "  listMedia(): Promise<ResourceEnvelope<MediaResource[]>>", "  uploadMedia(file: File): Promise<ResourceEnvelope<MediaResource>>", "  deleteMedia(id: string): Promise<ResourceEnvelope<{ deleted: boolean }>>")
		implementations = append(implementations, "    listMedia: () => client.request<ResourceEnvelope<MediaResource[]>>('/api/media'),", "    uploadMedia: (file) => { const body = new FormData(); body.append('file', file); return client.request<ResourceEnvelope<MediaResource>>('/api/media', { method: 'POST', body }) },", "    deleteMedia: (id) => client.request<ResourceEnvelope<{ deleted: boolean }>>('/api/media/' + encodeURIComponent(id), { method: 'DELETE' }),")
	}
	if hasAPIPath(document, "/api/audit") {
		methods = append(methods, "  listAudit(): Promise<ResourceEnvelope<AuditResource[]>>", "  getAudit(id: string): Promise<ResourceEnvelope<AuditResource>>")
		implementations = append(implementations, "    listAudit: () => client.request<ResourceEnvelope<AuditResource[]>>('/api/audit'),", "    getAudit: (id) => client.request<ResourceEnvelope<AuditResource>>(itemPath('/api/audit', id)),")
	}
	if hasAPIPath(document, "/api/extensions") {
		methods = append(methods, "  listExtensions(): Promise<ResourceEnvelope<ExtensionResource[]>>", "  getExtension(id: string): Promise<ResourceEnvelope<ExtensionResource>>", "  setPluginState(id: string, state: 'enabled' | 'disabled'): Promise<ResourceEnvelope<ExtensionResource[]>>")
		implementations = append(implementations, "    listExtensions: () => client.request<ResourceEnvelope<ExtensionResource[]>>('/api/extensions'),", "    getExtension: (id) => client.request<ResourceEnvelope<ExtensionResource>>(itemPath('/api/extensions', id)),", "    setPluginState: (id, state) => client.request<ResourceEnvelope<ExtensionResource[]>>(itemPath('/api/extensions', id), jsonOptions('PUT', { state })),")
	}
	return "/* eslint-disable */\n// This file is generated by admin-gen api. Do not edit by hand.\n\nimport type { ApiClient } from '@/core/api/client'\n\nimport type { " + strings.Join(imports, ", ") + ", ResourceEnvelope, ResourceListQuery } from './models'\n\nexport interface GeneratedApiClient {\n" + strings.Join(methods, "\n") + "\n}\n\n" + apiClientHelpers + "\nexport function createGeneratedApiClient(client: ApiClient): GeneratedApiClient {\n  return {\n" + strings.Join(implementations, "\n") + "\n  }\n}\n"
}

const apiClientHelpers = `function withQuery(path: string, query?: ResourceListQuery): string {
  if (!query) return path
  const params = new URLSearchParams()
  if (query.page !== undefined) params.set('page', String(query.page))
  if (query.perPage !== undefined) params.set('per_page', String(query.perPage))
  if (query.search?.trim()) params.set('search', query.search.trim())
  if (query.namespace?.trim()) params.set('namespace', query.namespace.trim())
  if (query.sort) { params.set('sort', query.sort.field); params.set('sort_dir', query.sort.direction) }
  for (const [field, value] of Object.entries(query.filters ?? {}).sort(([left], [right]) => left.localeCompare(right))) params.set('filter[' + field + ']', value)
  const serialized = params.toString()
  return serialized ? path + '?' + serialized : path
}
function itemPath(path: string, id: string): string { return path + '/' + encodeURIComponent(id) }
function jsonOptions(method: string, body: unknown): RequestInit { return { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } }`
