package generator

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

type ModuleOptions struct {
	RootDir    string
	ModuleRoot string
	Name       string
}

var moduleNamePattern = regexp.MustCompile(`^[a-z][a-z0-9-]*$`)

func GenerateModule(options ModuleOptions) error {
	if !moduleNamePattern.MatchString(options.Name) {
		return fmt.Errorf("module name must match %s: %q", moduleNamePattern.String(), options.Name)
	}
	rootDir := options.RootDir
	if rootDir == "" {
		rootDir = "."
	}
	moduleRoot := options.ModuleRoot
	if moduleRoot == "" {
		moduleRoot = filepath.Join(rootDir, "modules")
	}
	moduleDir := filepath.Join(moduleRoot, options.Name)
	if _, err := os.Stat(moduleDir); err == nil {
		return fmt.Errorf("module already exists: %s", options.Name)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect module directory: %w", err)
	}

	displayName := titleWords(options.Name)
	packageName := strings.ReplaceAll(options.Name, "-", "_")
	files := map[string]string{
		"module.yaml":               fmt.Sprintf("id: %s\nname: %s Module\nversion: 0.1.0\nruntime: compiled\ndependencies: []\nbackend: backend\nadmin: admin\n", options.Name, displayName),
		"README.md":                 fmt.Sprintf("# %s Module\n\nThis module is generated by `admin-gen module` and is ready for independent backend and admin implementation.\n", displayName),
		"acceptance.md":             fmt.Sprintf("# %s Module Acceptance\n\n- The module id is `%s`.\n- The module contract files are present.\n- Backend and admin implementation can be checked independently.\n", displayName, options.Name),
		"backend/README.md":         fmt.Sprintf("# %s backend\n\nAdd the compiled Go module implementation in this boundary.\n", displayName),
		"backend/go.mod":            fmt.Sprintf("module go-vue-admin-module/%s\n\ngo 1.25.0\n\nrequire goravel v0.0.0\n\nreplace goravel => ../../../backend\n", options.Name),
		"backend/module.go":         fmt.Sprintf("package %s\n\nimport platformmodule \"goravel/app/core/module\"\n\ntype Module struct{}\n\nfunc (Module) Name() string { return \"%s\" }\n\nfunc (Module) Register(_ platformmodule.Application) error { return nil }\n\nfunc (Module) Boot(_ platformmodule.Application) error { return nil }\n", packageName, options.Name),
		"backend/module_test.go":    fmt.Sprintf("package %s\n\nimport \"testing\"\n\nfunc TestModuleIdentity(t *testing.T) {\n\tif got := (Module{}).Name(); got != \"%s\" {\n\t\tt.Fatalf(\"module name = %%q\", got)\n\t}\n}\n", packageName, options.Name),
		"admin/package.json":        fmt.Sprintf("{\n  \"name\": \"@go-vue-admin/%s-admin\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"version\": \"0.1.0\"\n}\n", options.Name),
		"admin/module.ts":           fmt.Sprintf("import { defineAdminModule } from '../../../admin/src/core/extensions'\n\nexport const moduleDefinition = defineAdminModule({\n  id: '%s',\n  resources: [],\n  routes: [],\n  navigation: [],\n  locales: { 'zh-CN': {}, en: {} },\n})\n", options.Name),
		"admin/locales/README.md":   fmt.Sprintf("# %s locales\n\nAdd locale resources for the module here.\n", displayName),
		"admin/routes/README.md":    fmt.Sprintf("# %s routes\n\nAdd route definitions for the module here.\n", displayName),
		"admin/resources/README.md": fmt.Sprintf("# %s resources\n\nAdd Resource Engine definitions for the module here.\n", displayName),
	}

	for relativePath, content := range files {
		path := filepath.Join(moduleDir, filepath.FromSlash(relativePath))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func titleWords(value string) string {
	parts := strings.Split(value, "-")
	for index, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, " ")
}
