// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
	"goravel/app/models"
)

type MdepartmentsCreateDepartmentsTable struct{}

func (m *MdepartmentsCreateDepartmentsTable) Signature() string {
	return "create_departments_table"
}

func (m *MdepartmentsCreateDepartmentsTable) Up() error {
	if err := facades.Schema().Create("departments", func(table schema.Blueprint) {
		table.ID()
		table.String("name")
		table.String("code")
		table.String("status")
		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	}); err != nil {
		return err
	}
	for _, permission := range []models.Permission{
		{Name: "admin.departments.view", DisplayName: "Departments.view"},
		{Name: "admin.departments.create", DisplayName: "Departments.create"},
		{Name: "admin.departments.update", DisplayName: "Departments.update"},
		{Name: "admin.departments.delete", DisplayName: "Departments.delete"},
	} {
		exists, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission.Name).Exists()
		if err != nil {
			return err
		}
		if !exists {
			if err := facades.Orm().Query().Create(&permission); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *MdepartmentsCreateDepartmentsTable) Down() error {
	for _, permission := range []string{
		"admin.departments.view",
		"admin.departments.create",
		"admin.departments.update",
		"admin.departments.delete",
	} {
		if _, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission).Delete(); err != nil {
			return err
		}
	}
	return facades.Schema().DropIfExists("departments")
}
