// Code generated by admin:make-resource. DO NOT EDIT.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
	"goravel/app/models"
)

type MannouncementsCreateAnnouncementsTable struct{}

func (m *MannouncementsCreateAnnouncementsTable) Signature() string {
	return "create_announcements_table"
}

func (m *MannouncementsCreateAnnouncementsTable) Up() error {
	if err := facades.Schema().Create("announcements", func(table schema.Blueprint) {
		table.ID()
		table.String("title")
		table.String("status")
		table.DateTimeTz("created_at").Nullable()
		table.DateTimeTz("updated_at").Nullable()
	}); err != nil {
		return err
	}
	for _, permission := range []models.Permission{
		{Name: "admin.announcements.view", DisplayName: "Announcements.view"},
		{Name: "admin.announcements.create", DisplayName: "Announcements.create"},
		{Name: "admin.announcements.update", DisplayName: "Announcements.update"},
		{Name: "admin.announcements.delete", DisplayName: "Announcements.delete"},
	} {
		exists, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission.Name).Exists()
		if err != nil {
			return err
		}
		if !exists {
			if err := facades.Orm().Query().Create(&permission); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *MannouncementsCreateAnnouncementsTable) Down() error {
	for _, permission := range []string{
		"admin.announcements.view",
		"admin.announcements.create",
		"admin.announcements.update",
		"admin.announcements.delete",
	} {
		if _, err := facades.Orm().Query().Model(&models.Permission{}).Where("name = ?", permission).Delete(); err != nil {
			return err
		}
	}
	return facades.Schema().DropIfExists("announcements")
}
