// Code generated by admin:make-resource. Review before execution.
package migrations

import (
	"github.com/goravel/framework/contracts/database/schema"

	"goravel/app/facades"
)

type M20260922000004AddDepartmentsParentID struct{}

func (m *M20260922000004AddDepartmentsParentID) Signature() string {
	return "add_departments_parent_id"
}

func (m *M20260922000004AddDepartmentsParentID) Up() error {
	return facades.Schema().Table("departments", func(table schema.Blueprint) {
		table.Integer("parent_id").Nullable()
	})
}

func (m *M20260922000004AddDepartmentsParentID) Down() error {
	return facades.Schema().Table("departments", func(table schema.Blueprint) {
		table.DropColumn("parent_id")
	})
}
