// Code generated by admin:make-resource. DO NOT EDIT.
package permissions

const (
	DepartmentsView   = "admin.departments.view"
	DepartmentsCreate = "admin.departments.create"
	DepartmentsUpdate = "admin.departments.update"
	DepartmentsDelete = "admin.departments.delete"
)

var All = []string{DepartmentsView, DepartmentsCreate, DepartmentsUpdate, DepartmentsDelete}
