// Code generated by admin:make-resource. DO NOT EDIT.
export const resourceDefinition = {
  name: "departments",
  label: "Departments",
  route: "/departments",
  permission: "admin.departments.view",
  icon: "box",
  pageMode: "generic",
  navigation: { group: "business", order: 100 },

  actions: [{ name: "view", label: "View", kind: "", permission: "admin.departments.view", batch: false, payload: "" }, { name: "create", label: "Create", kind: "", permission: "admin.departments.create", batch: false, payload: "" }, { name: "update", label: "Update", kind: "", permission: "admin.departments.update", batch: false, payload: "" }, { name: "delete", label: "Delete", kind: "", permission: "admin.departments.delete", batch: false, payload: "" }],
  relations: [],
  form_groups: [],
  details: [],
  fields: [{ name: "name", label: "Name", type: "text", required: true, visible: true, readable: true, writable: true, sensitive: false }, { name: "code", label: "Code", type: "text", required: true, visible: true, readable: true, writable: true, sensitive: false }, { name: "status", label: "Status", type: "select", required: true, visible: true, readable: true, writable: true, sensitive: false, options: [{ value: "active", label: "Active" }, { value: "disabled", label: "Disabled" }] }],
} as const;
