#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODULE_ROOT="${MODULE_ROOT:-$ROOT_DIR/modules}"

fail() {
  echo "make-module: $*" >&2
  exit 1
}

[[ $# -eq 1 ]] || fail "usage: $0 <module-name>"
NAME="$1"
[[ "$NAME" =~ ^[a-z][a-z0-9-]*$ ]] || fail "module name must match ^[a-z][a-z0-9-]*$"

MODULE_DIR="$MODULE_ROOT/$NAME"
[[ ! -e "$MODULE_DIR" ]] || fail "module already exists: $NAME"

DISPLAY_NAME="$(printf '%s\n' "${NAME//-/ }" | awk '{ for (i = 1; i <= NF; i++) { $i = toupper(substr($i, 1, 1)) substr($i, 2) } print }')"
PACKAGE_NAME="${NAME//-/_}"
mkdir -p "$MODULE_DIR/backend" "$MODULE_DIR/admin/locales" "$MODULE_DIR/admin/routes" "$MODULE_DIR/admin/resources"

write_file() {
  local path="$1"
  local content="$2"
  printf '%s\n' "$content" > "$path"
}

write_file "$MODULE_DIR/module.yaml" "id: $NAME
name: $DISPLAY_NAME Module
version: 0.1.0
runtime: compiled
dependencies: []
backend: backend
admin: admin"

write_file "$MODULE_DIR/README.md" "# $DISPLAY_NAME Module

This module is generated by \`scripts/make-module.sh\` and is ready for independent backend and admin implementation."

write_file "$MODULE_DIR/acceptance.md" "# $DISPLAY_NAME Module Acceptance

- The module id is \`$NAME\`.
- The module contract files are present.
- Backend and admin implementation can be checked independently."

write_file "$MODULE_DIR/backend/README.md" "# $DISPLAY_NAME backend

Add the compiled Go module implementation in this boundary."

write_file "$MODULE_DIR/backend/go.mod" "module go-vue-admin-module/$NAME

go 1.25.0

require goravel v0.0.0

replace goravel => ../../../backend"

write_file "$MODULE_DIR/backend/module.go" "package $PACKAGE_NAME

import platformmodule \"goravel/app/core/module\"

type Module struct{}

func (Module) Name() string { return \"$NAME\" }

func (Module) Register(_ platformmodule.Application) error { return nil }

func (Module) Boot(_ platformmodule.Application) error { return nil }"

write_file "$MODULE_DIR/backend/module_test.go" "package $PACKAGE_NAME

import \"testing\"

func TestModuleIdentity(t *testing.T) {
  if got := (Module{}).Name(); got != \"$NAME\" {
    t.Fatalf(\"module name = %q\", got)
  }
}"

write_file "$MODULE_DIR/admin/package.json" "{
  \"name\": \"@go-vue-admin/$NAME-admin\",
  \"private\": true,
  \"type\": \"module\",
  \"version\": \"0.1.0\"
}"

write_file "$MODULE_DIR/admin/module.ts" "import { defineAdminModule } from '../../../admin/src/core/extensions'

export const moduleDefinition = defineAdminModule({
  id: '$NAME',
  resources: [],
  routes: [],
  navigation: [],
  locales: { 'zh-CN': {}, en: {} },
})"

write_file "$MODULE_DIR/admin/locales/README.md" "# $DISPLAY_NAME locales

Add locale resources for the module here."
write_file "$MODULE_DIR/admin/routes/README.md" "# $DISPLAY_NAME routes

Add route definitions for the module here."
write_file "$MODULE_DIR/admin/resources/README.md" "# $DISPLAY_NAME resources

Add Resource Engine definitions for the module here."

echo "make-module: generated modules/$NAME"
