// Code generated by admin:make-resource. DO NOT EDIT.
package menus

type Entry struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

var Announcements = Entry{Name: "announcements", Label: "Announcements", Route: "/announcements", Permission: "admin.announcements.view", Icon: "box"}
