// Code generated by admin:make-resource. DO NOT EDIT.
package menus

type Entry struct {
	Name       string
	Label      string
	Route      string
	Permission string
	Icon       string
}

var Departments = Entry{Name: "departments", Label: "Departments", Route: "/departments", Permission: "admin.departments.view", Icon: "box"}
